services:
    MetaModels\NoteListBundle\Storage\StorageAdapterFactory:
        public: false
    # deprecated since 1.1 and to be removed in 2.0.
    metamodels-notelist.storage-factory:
        alias: MetaModels\NoteListBundle\Storage\StorageAdapterFactory
        public: true

    MetaModels\NoteListBundle\NoteListFactory:
        arguments:
            - '@event_dispatcher'
            - '@database_connection'
            - '@MetaModels\NoteListBundle\Storage\StorageAdapterFactory'
            - '@metamodels.filter_setting_factory'
        public: false
    # deprecated since 1.1 and to be removed in 2.0.
    metamodels-notelist.factory:
        alias: MetaModels\NoteListBundle\NoteListFactory
        public: true

    MetaModels\NoteListBundle\Form\FormBuilder:
        public: false
    # deprecated since 1.1 and to be removed in 2.0.
    metamodels-notelist.form-builder:
        alias: MetaModels\NoteListBundle\Form\FormBuilder
        public: true

    MetaModels\NoteListBundle\Filter\NoteListFilterSettingTypeFactory:
        arguments:
            - '@MetaModels\NoteListBundle\NoteListFactory'
        public: false
        tags:
          - { name: metamodels.filter_factory }
    # deprecated since 1.1 and to be removed in 2.0.
    metamodels-notelist.filter-setting-factory:
        alias: MetaModels\NoteListBundle\Filter\NoteListFilterSettingTypeFactory
        public: true

    MetaModels\NoteListBundle\InsertTags:
        arguments:
            - '@MetaModels\NoteListBundle\NoteListFactory'
            - '@metamodels.factory'
        public: false
    # deprecated since 1.1 and to be removed in 2.0.
    metamodels-notelist.insert-tags:
        alias: MetaModels\NoteListBundle\InsertTags
        public: true
