services:
    MetaModels\NoteListBundle\Storage\StorageAdapterFactory:
        private: true
    metamodels-notelist.storage-factory:
        alias: MetaModels\NoteListBundle\Storage\StorageAdapterFactory
        public: true
        deprecated: The "%service_id%" service alias is deprecated since 1.1 and will be removed in 2.0.

    MetaModels\NoteListBundle\NoteListFactory:
        arguments:
            - '@event_dispatcher'
            - '@database_connection'
            - '@MetaModels\NoteListBundle\Storage\StorageAdapterFactory'
            - '@metamodels.filter_setting_factory'
        private: true
    metamodels-notelist.factory:
        alias: MetaModels\NoteListBundle\NoteListFactory
        public: true
        deprecated: The "%service_id%" service alias is deprecated since 1.1 and will be removed in 2.0.

    MetaModels\NoteListBundle\Form\FormBuilder:
        arguments:
            - '@database_connection'
        private: true
    metamodels-notelist.form-builder:
        alias: MetaModels\NoteListBundle\Form\FormBuilder
        public: true
        deprecated: The "%service_id%" service alias is deprecated since 1.1 and will be removed in 2.0.

    MetaModels\NoteListBundle\Filter\NoteListFilterSettingTypeFactory:
        arguments:
            - '@MetaModels\NoteListBundle\NoteListFactory'
        private: true
        tags:
          - { name: metamodels.filter_factory }
    metamodels-notelist.filter-setting-factory:
        alias: MetaModels\NoteListBundle\Filter\NoteListFilterSettingTypeFactory
        public: true
        deprecated: The "%service_id%" service alias is deprecated since 1.1 and will be removed in 2.0.

    MetaModels\NoteListBundle\InsertTags:
        arguments:
            - '@MetaModels\NoteListBundle\NoteListFactory'
            - '@metamodels.factory'
        private: true
    metamodels-notelist.insert-tags:
        alias: MetaModels\NoteListBundle\InsertTags
        public: true
        deprecated: The "%service_id%" service alias is deprecated since 1.1 and will be removed in 2.0.
